In [1]:
import numpy as np
from datetime import date, timedelta

# 1. Create a 3x3x3 array with random values

In [2]:
arr = np.random.rand(3,3,3)
arr

array([[[0.92850302, 0.73919635, 0.84206853],
        [0.8616611 , 0.18171448, 0.90139403],
        [0.22098264, 0.60061041, 0.28412271]],

       [[0.82450781, 0.51480726, 0.37141686],
        [0.98959077, 0.87489657, 0.48313067],
        [0.41557947, 0.28035863, 0.96703823]],

       [[0.38778704, 0.45490197, 0.12820483],
        [0.52206896, 0.58710822, 0.98890799],
        [0.03259626, 0.99586361, 0.14353085]]])

# 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
arr = np.diag(np.arange(4) + 1, k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [5]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
arr

array([[-0.74701373, -1.31227247, -0.97229153,  0.7084966 , -0.2104636 ],
       [ 1.14117903, -0.63824424, -1.26978418,  1.30806708,  0.89302754],
       [ 0.47311067,  1.03125131, -1.3296033 ,  1.10082713, -1.00248539],
       [-0.50131685, -0.28789059, -1.07563141, -1.21970371,  1.28247242],
       [-1.26839927,  0.83012628,  1.00329987,  1.21759373,  0.84564862]])

# 5. How to find common values between two arrays

In [6]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

np.intersect1d(arr1, arr2)

array([0, 2, 3, 8])

# 6. How to get the dates of yesterday, today and tomorrow?

In [7]:


yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)



2020-07-24 2020-07-25 2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [8]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

equal = np.array_equal(arr1,arr2)
print(f'Array1:\n{arr1}\n\n')
print(f'Array2:\n{arr2}\n\n')
print(f'Equality: {equal}')

Array1:
[[0.92845805 0.43494912 0.81350698]
 [0.64522139 0.02263964 0.80265298]
 [0.07154516 0.10439579 0.6907268 ]]


Array2:
[[0.27574463 0.23372427 0.53609197]
 [0.63123108 0.39197866 0.07493047]
 [0.33216205 0.36328452 0.08761289]]


Equality: False


# 8. Create random vector of size 10 and replace the maximum value by 0

In [9]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.5935949 , 0.20858658, 0.1975453 , 0.14509783, 0.61530003,
       0.        , 0.71979513, 0.87086682, 0.26411215, 0.70981029])

# 9. How to print all the values of an array?

In [10]:
arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 10. Subtract the mean of each row of a matrix

In [11]:
arr = np.random.rand(3,3)
arr_mean = arr - arr.mean(axis=1, keepdims=True)

arr_mean

array([[-0.12152749,  0.42487012, -0.30334263],
       [ 0.204689  ,  0.03332378, -0.23801278],
       [-0.13323134, -0.19448085,  0.32771219]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [12]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([4., 2., 2., 3., 4.])

# 12. How to get the diagonal of a dot product?

In [13]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([ 85, 111, 200])

# 13. How to find the most frequent value in an array?

In [14]:
arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)

[6 9 0 4 1 9 6 4 9 3 2 0 3 6 8 9 8 1 9 1]


9

# 14. How to get the n largest values of an array

In [15]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

2

# 15. How to create a record array from a regular array?

In [16]:
arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])